급상승 질문 API
boostcampwm2023/web04-ALGOCEAN pull request #172
Opened 2023-11-29 08:45 UTC by seungy0

급상승 질문 API 구현
{Id: number, Title: string} 응답 또는 404 응답하게 구현했습니다.

DB에 ViewLog 테이블 추가했습니다.

2023-11-29 11:39 UTC, perArdua requested changes

2023-11-29 16:38 UTC, seungy0 commented on BE/src/questions/questions.service.ts
> +        Title: true,
이게 고민인게 저희 사이트 들어가보면 급상승 질문이 뭔지 내용이 메인페이지에 나와서요.
명세대로하면 고치는 게 맞긴합니다만 어떻게하는게 좋을까요?
리다이렉트하게만 하면 메인페이지에는 급상승 질문 내용 띄우기는 어려울거에요. @MayOwall @BaeJ1H021

2023-11-29 16:39 UTC, seungy0 commented on BE/src/questions/questions.controller.ts
> +    return trendingQuetion;
이게 고민인게 저희 사이트 들어가보면 급상승 질문이 뭔지 내용이 메인페이지에 나와서요.
명세대로하면 고치는 게 맞긴합니다만 어떻게하는게 좋을까요?
리다이렉트하게만 하면 메인페이지에는 급상승 질문 내용 띄우기는 어려울거에요. @MayOwall @BaeJ1H021

2023-11-30 17:47 UTC, MayOwall commented on BE/src/questions/questions.controller.ts
> +    return trendingQuetion;
저는 승규님 의견에 동의합니다.
figma 디자인과 사용자 경험을 생각하면 승규님 의견이 더 적합한 것 같아요.

2023-12-01 03:28 UTC, perArdua approved these changes

2023-12-01 03:28 UTC, perArdua commented on BE/src/questions/questions.controller.ts
> +    return trendingQuetion;
제가 작성한 redirect하는 기존 API들 수정하겠습니다.

2023-12-01 03:50 UTC, merged

2023-12-01 10:00 UTC, seungy0 commented on BE/src/questions/questions.controller.ts
> +    return trendingQuetion;
넵