인증 관련 코드 삽입
boostcampwm2023/web04-ALGOCEAN pull request #265
Opened 2023-12-11 18:34 UTC by perArdua

### 관련 이슈
#200 

### 구현한 기능
- 회원가입시 입력한 user의 id로 user의 pk를 알아내는 기능 구현
- UseGuards가 필요한 곳에 모두 적용

2023-12-12 08:13 UTC, seungy0 reviewed
기존 코드에서 req.user.id로 가져올 수 있는걸로 알고 있는데 아닌가요?

2023-12-12 08:54 UTC, perArdua commented
ㅜㅜ

2023-12-12 09:10 UTC, perArdua commented
@seungy0 수정했습니다.

2023-12-13 05:21 UTC, seungy0 approved these changes
고생하셨습니다👍👍

2023-12-13 05:26 UTC, seungy0 requested changes
지금 상태에서 swagger 잘 되는지 궁금하네요. 
@ApiBearerAuth('access-token')
@ApiBearerAuth('Authorization')으로 바꾸기로 한거 아니었나요?

2023-12-13 08:25 UTC, perArdua commented
어제 분명히 푸시 했다고 생각했는데
푸시가 안됐었네요
![image](https://github.com/boostcampwm2023/web04-ALGOCEAN/assets/70432496/d5ec4438-6411-4270-9732-eafa0ab323ab)

2023-12-13 10:12 UTC, seungy0 approved these changes
확인했습니당

2023-12-13 11:01 UTC, merged