prisma 설정
boostcampwm2023/web04-ALGOCEAN pull request #46
Opened 2023-11-14 13:21 UTC by perArdua

### 관련 이슈
#45 

### 구현한 기능
- gitignore에 env 추가
- node_modules 사용하도록 함
- prisma, prisma/client module 설치
- prisma schema 생성

⚠️ 확인할 사항 ⚠️
- [x] 제목에 PR 내용을 한문장으로 요약했나요?
- [x] pull request와 issue를 연동시켰나요?
- [x] 적절한 라벨을 달았나요?

2023-11-14 14:24 UTC, seungy0 requested changes

2023-11-14 14:24 UTC, seungy0 commented on BE/.yarnrc.yml
> +nodeLinker: node-modules
node_modules 다시 활성화하신 부분 확인했습니다.

2023-11-14 14:24 UTC, seungy0 commented on BE/package.json
> +    "@yarnpkg/pnpify": "^4.0.1",
pnpify를 설치하셨네요

2023-11-14 14:24 UTC, seungy0 commented on BE/prisma/schema.prisma
> +  questions  questions? @relation(fields: [QuestionId], references: [Id], onDelete: NoAction, onUpdate: NoAction, map: "answers_ibfk_2")
다 대문자로 하다가 이 부분이 소문자인게 킹받네요. 그리고 테이블 이름 첫 글자가 소문자가 됐는데 의도하신 건가요?

2023-11-14 14:45 UTC, seungy0 commented
귀찮으시겠지만 PR, commit 메시지에 좀 더 내용 넣어주시면 코드 리뷰에 도움될 것 같습니다.

2023-11-14 14:51 UTC, seungy0 commented on BE/prisma/schema.prisma
> +}
ProgrammingLaguage가 빠졌습니다.

2023-11-14 15:00 UTC, perArdua commented on BE/prisma/schema.prisma
> +}
추가하겠습니다. 아까 노션에 옮겨 적을 때 적었던 것 같은데 왜 빠져있는지 모르겠네요

2023-11-14 15:00 UTC, perArdua commented on BE/package.json
> +    "@yarnpkg/pnpify": "^4.0.1",
네 PnP환경에서 Prisma를 사용하기 위해 pnpify를 설치했습니다

2023-11-14 15:00 UTC, perArdua commented on BE/prisma/schema.prisma
> +  questions  questions? @relation(fields: [QuestionId], references: [Id], onDelete: NoAction, onUpdate: NoAction, map: "answers_ibfk_2")
대/소문자 관련 부분도 수정하겠습니다

2023-11-14 15:01 UTC, perArdua commented
어떤 의도로 무엇을 했는지 작성하는 부분이 부족했고, 제 코드 확인하는 과정에서 잘못된 부분을 바로잡는 과정이 부족했다고 생각이 되네요. 추후 PR에서 고쳐보겠습니다.

2023-11-14 18:08 UTC, perArdua commented on BE/prisma/schema.prisma
> +  questions  questions? @relation(fields: [QuestionId], references: [Id], onDelete: NoAction, onUpdate: NoAction, map: "answers_ibfk_2")
대/소문자 관련 부분 해결이 안되네요.

2023-11-15 03:33 UTC, seungy0 commented on BE/prisma/schema.prisma
> +  questions  questions? @relation(fields: [QuestionId], references: [Id], onDelete: NoAction, onUpdate: NoAction, map: "answers_ibfk_2")
DB 연결을 잘못하셔서 그렇네요. 천천히 해결해보시죠!

2023-11-15 03:33 UTC, seungy0 commented on BE/prisma/schema.prisma
> +}
추가했습니다

2023-11-15 03:34 UTC, seungy0 approved these changes

2023-11-15 03:35 UTC, merged

2023-11-15 08:24 UTC, perArdua reviewed
commit message 확인했습니다.

2023-11-15 08:24 UTC, perArdua commented on BE/.pnp.cjs
PnP를 사용하지 않는 이유로 파일 삭제한 것 확인했습니다.

2023-11-15 08:24 UTC, perArdua commented on BE/.pnp.loader.mjs
PnP를 사용하지 않는 이유로 파일 삭제한 것 확인했습니다.

2023-11-15 08:24 UTC, perArdua commented on BE/prisma/schema.prisma
합의된 내용으로 schema.prisma 변경한 부분 확인했습니다.
추가적으로 말씀해주신 defalut value는 추가되지 않았습니다.

2023-11-15 08:26 UTC, perArdua commented on BE/prisma/schema.prisma
> +  questions  questions? @relation(fields: [QuestionId], references: [Id], onDelete: NoAction, onUpdate: NoAction, map: "answers_ibfk_2")
네 저는 query string으로 ssh 관련 정보를 넘기면 ssh 연결이 되는 줄 알았는데 아니었습니다.
말씀해주신대로 local에서의 MySQL를 종료해보니 prisma db pull 명령어를 실행했을 때 오류가 나더라구요.

2023-11-21 16:11 UTC, seungy0 commented on BE/prisma/schema.prisma
이걸 놓쳤네요. #89 여기서 추가하겠습니다.