단일 질문 생성 API
boostcampwm2023/web04-ALGOCEAN pull request #60
Opened 2023-11-16 10:46 UTC by perArdua

### 관련 이슈
#52 

### 구현한 기능

notion의 API 명세에 나와있는 대로 Request Body를 위한 DTO를 만들었습니다.

questions.service.ts 에서는 DTO와 UserId를 이용하여 question을 생성하게 했습니다.

questions.controller.ts 에서는 questionService를 활용하여 DTO와 UserId를 토대로 question 생성을 요청하도록 했습니다.

이때 DTO의 값이 검증에 실패하는 경우에는 BAD_REQUEST를 반환하고 question 생성에 실패한 경우에는INTERNAL_SERVER_ERROR를 반환하고 성공한 경우에는 CREATED를 반환하도록 했습니다.

2023-11-16 15:28 UTC, seungy0 requested changes
conflict 해결해주세요. 아래에 있는 resolve conflict 버튼 물러서 해결하시거나 ide에서 해결하시면 될 것 같습니다.

2023-11-16 15:28 UTC, seungy0 commented on BE/src/questions/questions.service.ts
> +  // TODO: Implement logic to associate the question with the user by including the user id
이거 이미 수행한 TODO 아닌가요? 구현된거라면 지워주세요.

2023-11-16 15:39 UTC, perArdua commented on BE/src/questions/questions.service.ts
> +  // TODO: Implement logic to associate the question with the user by including the user id
UserGuard와 Decorator를 활용하여 User의 정보를 Controller에서 받아오는 과정이 없다고 생각하여 지우지 않았는데 승규님께서 말씀하신 것을 보고 다시 생각해보니까 이미 수행한 TODO에 분류되네요 지우겠습니다.

2023-11-16 18:12 UTC, perArdua commented
conflict 해결했습니다.

2023-11-17 16:47 UTC, seungy0 approved these changes
고생하셨습니다

2023-11-17 16:55 UTC, merged