단일 질문 삭제 API
boostcampwm2023/web04-ALGOCEAN pull request #61
Opened 2023-11-16 11:16 UTC by perArdua

### 관련 이슈
#54 

### 구현한 기능

questions.controller.ts 에서는 questionService를 활용하여 QuestionId와 UserId를 토대로 question 삭제를 요청하도록 했습니다.

이때 QuestionId에 해당하는 question이 존재하지 않거나 이미 채택된 경우에는 NOT_FOUND를 반환하고 위의 경우가 아닌데 question을 작성한 User가 삭제 요청한 것이 아니라면  FORBIDDEN을 반환하고 삭제가 성공하는 경우에는 OK를 반환하고 그 외의 경우 INTERNAL_SERVER_ERROR를 반환하도록 했습니다.

2023-11-16 15:30 UTC, seungy0 requested changes
고생하셨습니다.

2023-11-16 15:30 UTC, seungy0 commented on BE/src/questions/questions.controller.ts
> +
질문 생성 PR에 들어간 내용이 여기에도 있네요. 의도하신건가요??

2023-11-16 15:30 UTC, seungy0 commented on BE/src/questions/questions.service.ts
> +  // TODO: check if user is owner of the question
TODO 주석 지워주세요. 이미 구현하신 내용인 것 같네요.

2023-11-16 15:41 UTC, perArdua commented on BE/src/questions/questions.controller.ts
> +
의도하지 않은 부분입니다.
인텔리제이 IDE에 있는 git 툴을 활용하면 변경점을 부분적으로 add할 수 있다는 것을 알게되서 그 부분을 활용을 했는데 제가 잘못 체크한 것 같습니다.
알려주셔서 감사합니다.

2023-11-16 15:41 UTC, perArdua commented on BE/src/questions/questions.controller.ts
> +
해당 부분 수정하겠습니다.

2023-11-16 15:42 UTC, perArdua commented on BE/src/questions/questions.service.ts
> +  // TODO: check if user is owner of the question
넵 이 부분도 제가 구현 안했다고 생각했는데 승규님 말씀 보고 다시 보니까 구현 한 내용이네요.
지우겠습니다.

2023-11-17 17:01 UTC, perArdua commented
conflict 해결 했습니다.

2023-11-18 13:54 UTC, seungy0 approved these changes

2023-11-18 13:54 UTC, seungy0 commented on BE/src/questions/questions.controller.ts
> +      }
이 부분의 else는 필요없어 보입니다. 중요한 부분은 아니고 스타일 차이인 것 같네요ㅎㅎ

2023-11-18 13:54 UTC, seungy0 commented on BE/src/questions/questions.service.ts
> +    return true;
이 부분이 조금 고민되네요. 저도 유사하게 구현했을 것 같긴합니다.

고민되는 부분이 두가지가 있습니다.
1. findUnique를 실행하고 delete를 실행하는 사이에 모종의 이유로(다른 클라이언트에서 삭제 등) row가 삭제될 일은 없을까? 이런 부분을 고려해야할까?

2. delete문을 그냥 실행하고 몇 개 쿼리를 지웠는지 확인만해도 되지 않을까 고민입니다.
```suggestion
  async deleteOneQuestion(id: number, userId: number): Promise<boolean> {
    const result = await this.prisma.question.delete({
      where: {
        Id: id,
        IsAdopted: false,
        User: {
          Id: userId,
        },
      },
    });

    if (!result.count) {
      throw new NotFoundException('Question not found or user is not the owner');
    }

    return true;
```

물론 이런 방식으로 하면 어떤 이유로 row가 삭제되었는지 명확히 알 수 없는 단점도 존재합니다.

태호님 생각은 어떤가요?

2023-11-21 10:19 UTC, merged